Major.create(korean: "============ 글로벌캠퍼스 ===========")
Major.create(korean: "============= 통번역대학 ============")
Major.create(korean: "영어통번역학부", english: "Eit", homepage: "http://english.hufs.ac.kr/" )
Major.create(korean: "독일어통번역학과", english: "Git", homepage: "http://hufsdeutsch.hufs.ac.kr/" )
Major.create(korean: "스페인어통번역학과", english: "Sit", homepage: "http://hufsit.hufs.ac.kr/")
Major.create(korean: "이탈리아통번역학과", english: "Iit", homepage: "http://italia.hufs.ac.kr/" )
Major.create(korean: "중국어통번역학과", english: "Cit", homepage: "http://china.hufs.ac.kr/" )
Major.create(korean: "일본어통번역학과", english: "Jit", homepage: "http://hufs.ac.kr/user/hufsjp/" )
Major.create(korean: "아랍어통번역학과", english: "Ait", homepage: "http://ait.hufs.ac.kr/" )
Major.create(korean: "말레이인도네시아어통번역학과", english: "Mit", homepage: "http://www.hufs.ac.kr/user/bahasa" )
Major.create(korean: "태국어통번역학과", english: "Tit", homepage: "http://www.hufs.ac.kr/user/thai/")

Major.create(korean: "============== 인문대학 =============")
Major.create(korean: "철학과", english: "Phil", homepage: "http://philosophy.hufs.ac.kr/")
Major.create(korean: "사학과", english: "His", homepage: "http://history.hufs.ac.kr/")
Major.create(korean: "언어인지학과", english: "Lcs", homepage: "http://linguistics.hufs.ac.kr/")
Major.create(korean: "지식컨텐츠학부", english: "Con", homepage: "http://www.hufscon.com/")
  
Major.create(korean: "============= 동유럽대학 ============")
Major.create(korean: "폴란드어학과", english: "Pol", homepage: "http://polski.hufs.ac.kr")
Major.create(korean: "루마니아어과", english: "Rum", homepage: "http://romania.hufs.ac.kr/")
Major.create(korean: "체코슬로바키아어과", english: "Czsl", homepage: "http://czechandslovak.hufs.ac.kr/")
Major.create(korean: "헝가리어과", english: "Hun", homepage: "http://hungary.hufs.ac.kr/")
Major.create(korean: "세르비아크로아티아어과", english: "Secr", homepage: "http://yugo.hufs.ac.kr/")
Major.create(korean: "우크라이나어과", english: "Ukr", homepage: "http://ukraine.hufs.ac.kr/")

Major.create(korean: "============ 국제지역대학 ===========")
Major.create(korean: "프랑스학과", english: "Gfra", homepage: "http://www.hufsfrance.com/")
Major.create(korean: "브라질학과", english: "Bra", homepage: "http://hufsbrazil.hufs.ac.kr/")
Major.create(korean: "그리스불가리아학과", english: "Grbu", homepage: "http://gb.hufs.ac.kr/")
Major.create(korean: "인도학과", english: "Ind", homepage: "http://www.hufs.ac.kr/user/hufsindia")
Major.create(korean: "중앙아시아학과", english: "Asia", homepage: "http://centralasia.hufs.ac.kr/")
Major.create(korean: "아프리카학부", english: "Afr", homepage: "http://africa.hufs.ac.kr/")
Major.create(korean: "러시아학과", english: "Grus", homepage: "http://russianstudies.hufs.ac.kr/")
Major.create(korean: "국제스포츠레저학부", english: "Spo", homepage: "http://sporthufs.com/")
Major.create(korean: "한국학과", english: "Kor", homepage: "http://koreanstudies.hufs.ac.kr/")

Major.create(korean: "============== 경상대학 =============")
Major.create(korean: "국제경영학과", english: "Ibus", homepage: "http://ibiz.hufs.ac.kr/")
Major.create(korean: "경제학과", english: "Gecn", homepage: "http://econ.hufs.ac.kr/")
Major.create(korean: "경영정보학과", english: "Mis",homepage:"http://mis.hufs.ac.kr/")
Major.create(korean: "GBT 학부", english: "Gbt", homepage:"http://gbt.hufs.ac.kr/")
Major.create(korean: "국제금융학과", english: "Inf", homepage:"http://if.hufs.ac.kr/")
  
Major.create(korean: "============ 자연과학대학 ===========")
Major.create(korean: "수학과", english: "Math", homepage: "http://math.hufs.ac.kr/")
Major.create(korean: "통계학과", english: "Stat", homepage: "http://stat.hufs.ac.kr/")
Major.create(korean: "전자물리학과", english: "Elph", homepage: "http://physics.hufs.ac.kr/")
Major.create(korean: "환경학과", english: "Env",  homepage:"http://www.envi.hufs.ac.kr/")
Major.create(korean: "생명공학과", english: "Bio",  homepage:"http://bio.hufs.ac.kr/")
Major.create(korean: "화학과", english: "Chem", homepage: "http://chemistry.hufs.ac.kr/")

Major.create(korean: "============== 공과대학 =============")
Major.create(korean: "컴퓨터전자시스템학부", english: "Ces", homepage: "http://ces.hufs.ac.kr/")
Major.create(korean: "정보통신공학과", english: "Ice", homepage: "http://ice.hufs.ac.kr/")
Major.create(korean: "전자공학과", english: "Elen", homepage: "http://ee.hufs.ac.kr/")
Major.create(korean: "산업경영공학과", english: "Ime", homepage: "http://ime.hufs.ac.kr/")

Major.create(korean: "======== 바이오메디컬공학부 =========")
Major.create(korean: "바이오메디컬공학부", english: "Bme", homepage: "http://bme.hufs.ac.kr/")
  
Major.create(korean: "============= 서울캠퍼스 ============")

Major.create(korean: "============== 영어대학 =============")
Major.create(korean: "ELLT / 영어학과", english: "Ellt", homepage: "http://hufseng.hufs.ac.kr/")
Major.create(korean: "영미문학문화학과", english: "Elit", homepage: "http://hufseng.hufs.ac.kr/")
Major.create(korean: "Eicc학과", english: "Eicc", homepage: "http://hufseng.hufs.ac.kr/")
Major.create(korean: "영어학부", english: "Eng", homepage: "http://hufseng.hufs.ac.kr/")
  
Major.create(korean: "============= 서양어대학 ============")
Major.create(korean: "프랑스어학부", english: "Sfra", homepage: "http://hufsfr.hufs.ac.kr/")
Major.create(korean: "독일어과", english: "Ger", homepage: "http://deutsch.hufs.ac.kr/")
Major.create(korean: "노어과", english: "Srus", homepage: "http://hufsrussia.hufs.ac.kr/")
Major.create(korean: "스페인어과", english: "Spa", homepage: "http://hufspain.hufs.ac.kr/")
Major.create(korean: "이탈리아어과", english: "Ita", homepage: "http://builder.hufs.ac.kr/user/italiano/")
Major.create(korean: "포르투갈어과", english: "Port", homepage: "http://portuguese.hufs.ac.kr/")
Major.create(korean: "네덜란드어과", english: "Neth", homepage: "http://neds.hufs.ac.kr/")
Major.create(korean: "스칸디나비아어과", english: "Scan", homepage: "http://builder.hufs.ac.kr/user/hufsscan/")
  
Major.create(korean:"======== 아시아언어문화대학 =========")
Major.create(korean:"말레이인도네시어어과", english: "Main", homepage: "http://hufsmain.hufs.ac.kr/")
Major.create(korean:"아랍어과", english: "Arab", homepage: "http://arab.hufs.ac.kr/")
Major.create(korean:"태국어과", english: "Tha", homepage: "http://thai.hufs.ac.kr/")
Major.create(korean:"베트남어과", english: "Viet", homepage: "http://vietnamhufs.co.kr/")
Major.create(korean:"인도어과", english: "Ind", homepage: "http://builder.hufs.ac.kr/user/india01")
Major.create(korean:"터키아제르바이잔어과", english: "Tur", homepage: "http://turkazeri.hufs.ac.kr/")
Major.create(korean:"이란어과", english: "Iran", homepage: "http://iran.hufs.ac.kr/")
Major.create(korean:"몽골어과", english: "Mon", homepage: "http://mongolian.hufs.ac.kr/")
  
Major.create(korean: "============= 중국어대학 ============")
Major.create(korean: "중국언어문화학부", english: "Chcu", homepage:"http://chufs1.hufs.ac.kr/")
Major.create(korean: "중국외교통상학부", english: "Chdi", homepage:"http://chufs2.hufs.ac.kr/")

Major.create(korean:"============= 일본어대학 ============")
Major.create(korean:"일본언어문화학부", english: "Jpcu", homepage: "http://www.hufsjapan.ac.kr/")
Major.create(korean:"융합일본지역학부", english: "Jpst", homepage: "http://www.hufsjapan.ac.kr/")
  
Major.create(korean:"============ 사회과학대학 ===========")
Major.create(korean:"정치외교학과", english: "Psc", homepage: "http://hufspol.hufs.ac.kr/")
Major.create(korean:"행정학과", english: "Adm", homepage: "http://hufspa.hufs.ac.kr/")
Major.create(korean:"미디어커뮤니케이션학부", english: "Com", homepage: "http://commu.hufs.ac.kr/")
  
Major.create(korean:"============== 법과대학 =============")
Major.create(korean:"법학과", english: "Law", homepage: "http://legal.hufs.ac.kr/")
  
Major.create(korean:"============== 상경대학 =============")
Major.create(korean:"국제통상학과", english: "Iel", homepage: "http://iel.hufs.ac.kr/")
Major.create(korean:"경제학부", english: "Secn", homepage: "http://econ.hufs.ac.kr/")

Major.create(korean:"============== 경영대학 =============")
Major.create(korean:"경영학부", english: "Bus", homepage: "http://biz.hufs.ac.kr/")

Major.create(korean:"============== 사범대학 =============")
Major.create(korean:"영어교육과", english: "Etc", homepage: "http://www.hufs.ac.kr/hufsee/")
Major.create(korean:"프랑스어교육과", english: "Ftc", homepage: "http://fe.hufs.ac.kr/")
Major.create(korean:"독일어교육과", english: "Gtc", homepage: "http://germanedu.hufs.ac.kr/")
Major.create(korean:"한국어교육과", english: "Ktc", homepage: "http://hufskle.hufs.ac.kr/")
Major.create(korean:"중국어교육과", english: "Ctc", homepage: "http://cle.hufs.ac.kr/")
  
Major.create(korean:"============== 국제학부 =============")
Major.create(korean:"국제학부", english: "Int", homepage: "http://hufsdis.hufs.ac.kr/")
  
Major.create(korean:"=============== LD학부 ==============")
Major.create(korean:"LD학부", english: "Ld", homepage: "http://ld.hufs.ac.kr/")
  
Major.create(korean:"=============== LT학부 ==============")
Major.create(korean:"LT학부", english: "Lt", homepage: "http://hufslt.hufs.ac.kr/")
